DELETE FROM facturacion.FACTURA_PRODUCTOS
DELETE FROM facturacion.FACTURAS
DELETE FROM registro.SERVICIOS_SOLICITADOS
DELETE FROM registro.MASCOTA_RESERVACION
DELETE FROM registro.MASCOTA_CONDICION --
DELETE FROM registro.MASCOTA_CONTACTO --
DELETE FROM registro.MASCOTA_VACUNA --
DELETE FROM registro.DUEÑOS_MASCOTA --
DELETE FROM registro.HISTORICO_SERVICIOS
DELETE FROM registro.HISTORICO_ESTATUS
DELETE FROM registro.MASCOTAS --
DELETE FROM registro.RESERVACIONES
DELETE FROM facturacion.FACTURAS_METODOS_PAGOS

CREATE TRIGGER 



CREATE TRIGGER insertarDueñosPrincipales
ON registro.DUEÑOS_MASCOTA
AFTER INSERT
AS
BEGIN
            DECLARE @Mascota_ID int, @Dueño_ID int
            SELECT @Mascota_ID = Mascota_ID, @Dueño_ID = Dueño_ID FROM inserted
			INSERT INTO registro.DUEÑOS_MASCOTA(Mascota_ID, Dueño_ID) VALUES (@Mascota_ID, @Dueño_ID)
END
