USE Hotel_Mascotas_DB

insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Fernandina', 'Gleave', '513-667-6495', 'fgleave0@cmu.edu', 48, 'Heath', '9335', '8/6/1976');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Donavon', 'Clancey', '509-858-0982', 'dclancey1@princeton.edu', 47, 'Farmco', '00', '7/22/1997');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Kaitlyn', 'Swiffin', '583-168-8295', 'kswiffin2@eventbrite.com', 32, 'Havey', '98', '1/2/1971');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Maire', 'Drew-Clifton', '359-990-6447', 'mdrewclifton3@chronoengine.com', 23, 'Darwin', '670', '7/15/1991');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Dolly', 'Stein', '967-926-8923', 'dstein4@slideshare.net', 31, 'Esch', '4', '9/9/1977');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Paloma', 'Playford', '397-441-1806', 'pplayford5@newyorker.com', 32, 'Commercial', '26973', '7/13/1972');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Mehetabel', 'Crudge', '441-857-7447', 'mcrudge6@imdb.com', 10, 'Oneill', '91586', '5/18/1976');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('De witt', 'Edis', '983-139-1752', 'dedis7@usatoday.com', 38, 'Fair Oaks', '9', '2/15/1997');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Tedie', 'Aspland', '252-326-9416', 'taspland8@flavors.me', 60, 'Ruskin', '9554', '7/2/1986');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Christiane', 'Rappoport', '425-829-6527', 'crappoport9@reference.com', 38, 'Forest Dale', '53259', '2/17/1984');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Starlin', 'Yitzovitz', '934-249-4135', 'syitzovitza@prweb.com', 68, 'Fieldstone', '8', '5/7/1986');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Stephen', 'Glanfield', '546-316-5451', 'sglanfieldb@toplist.cz', 47, 'Dayton', '592', '3/12/1976');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Micky', 'Banaszkiewicz', '442-616-4613', 'mbanaszkiewiczc@scientificamerican.com', 35, 'Sullivan', '65', '7/20/1970');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Eleanore', 'Fattori', '189-816-9425', 'efattorid@netlog.com', 40, 'Texas', '709', '5/21/1984');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Gerri', 'Comizzoli', '849-269-4925', 'gcomizzolie@cdc.gov', 52, 'Service', '81', '4/30/1969');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Krysta', 'Skally', '166-804-4094', 'kskallyf@virginia.edu', 62, 'Leroy', '235', '11/18/1971');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Blondell', 'Hindenburg', '628-674-1555', 'bhindenburgg@fc2.com', 33, 'Carpenter', '56262', '5/23/1989');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Brendon', 'Lockwood', '718-686-3462', 'blockwoodh@hud.gov', 49, 'Kingsford', '332', '12/15/1989');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Wyatt', 'Chalice', '637-516-0663', 'wchalicei@apache.org', 66, 'Parkside', '22131', '1/28/1994');
insert into adm.EMPLEADOS (Nombres, Apellidos, Telefono, Correo_Electronico, Sector_ID, Calle, Numero_Casa, Fecha_Nacimiento) values ('Andree', 'Matusevich', '108-670-2933', 'amatusevichj@wufoo.com', 9, 'Acker', '37397', '10/31/1984');
