--CONTACTO_EMERGENCIA

insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('at', 'Evvie', 'Piner', '676-934-3863', 2, 'Michigan', '6', 'epiner0@huffingtonpost.com', '1983-06-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('in', 'Cesaro', 'Bonde', '640-317-1590', 2, 'La Follette', '7488', 'cbonde1@sbwire.com', '1998-05-09', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('est', 'Aldwin', 'Gossling', '144-806-1883', 12, '5th', '42209', 'agossling2@tiny.cc', '1976-05-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vestibulum', 'Tammy', 'Akrigg', '437-399-1003', 2, 'Brown', '02', 'takrigg3@elegantthemes.com', '1982-10-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('curabitur', 'Bekki', 'Fowls', '361-164-3337', 5, 'Clemons', '8', 'bfowls4@indiatimes.com', '1989-09-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('montes', 'Kurt', 'Mouan', '855-533-8075', 4, 'West', '792', 'kmouan5@statcounter.com', '2001-07-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('cum', 'Eddy', 'Perkins', '486-392-1744', 7, 'Armistice', '88675', 'eperkins6@discovery.com', '1981-04-26', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('nibh', 'Marianna', 'Merlin', '991-521-4884', 4, 'Dixon', '2', 'mmerlin7@oakley.com', '1996-07-07', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eros', 'Nadiya', 'Manners', '736-780-9647', 1, 'Hudson', '997', 'nmanners8@flavors.me', '1996-12-27', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('luctus', 'Olly', 'Gamell', '388-902-6681', 11, 'East', '80', 'ogamell9@hp.com', '1977-03-12', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('blandit', 'Enrichetta', 'Stubbes', '539-515-4432', 12, 'Prairieview', '66', 'estubbesa@google.es', '1984-09-26', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ac', 'Pooh', 'Frank', '963-427-5546', 9, 'Mesta', '729', 'pfrankb@trellian.com', '1976-07-22', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('quam', 'Cosimo', 'Aspital', '627-429-6178', 2, 'Dayton', '3', 'caspitalc@altervista.org', '1977-12-28', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sit', 'Emmye', 'Olliffe', '814-131-1504', 4, 'Cordelia', '39393', 'eolliffed@cpanel.net', '1974-08-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('lectus', 'Lana', 'Redding', '567-579-4253', 1, 'Maywood', '03', 'lreddinge@plala.or.jp', '1977-01-12', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('justo', 'Noah', 'McGrill', '619-782-2323', 10, 'Helena', '9923', 'nmcgrillf@theglobeandmail.com', '2001-02-22', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sit', 'Mal', 'Haslewood', '997-644-9686', 7, 'Haas', '1211', 'mhaslewoodg@unblog.fr', '1984-07-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vivamus', 'Dorelia', 'Giurio', '860-150-5779', 4, 'Manitowish', '71', 'dgiurioh@infoseek.co.jp', '1989-12-12', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('metus', 'Carolee', 'Dorbon', '560-905-2456', 6, 'Shopko', '80', 'cdorboni@telegraph.co.uk', '1983-06-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('aliquet', 'Nickolas', 'Kubes', '246-147-9139', 13, 'Mallory', '667', 'nkubesj@ftc.gov', '1983-08-31', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('dictumst', 'Phillipp', 'Disbrey', '789-289-9905', 1, '1st', '7512', 'pdisbreyk@tuttocitta.it', '1993-01-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('interdum', 'Lauryn', 'Bauldry', '669-488-5831', 11, 'Dunning', '27299', 'lbauldryl@goo.gl', '1974-05-06', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('justo', 'Tiffany', 'Le Leu', '535-574-6669', 7, 'Johnson', '5193', 'tleleum@godaddy.com', '2002-05-06', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('in', 'Bailie', 'Spinnace', '799-146-9598', 3, 'Ridgeview', '2100', 'bspinnacen@nhs.uk', '1979-08-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('mauris', 'Toinette', 'Edgler', '252-938-9789', 11, 'Porter', '2', 'tedglero@dot.gov', '1973-09-23', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('interdum', 'Prescott', 'Gifford', '963-142-2427', 5, 'Lake View', '8', 'pgiffordp@soundcloud.com', '1983-06-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('integer', 'Sheridan', 'Gracewood', '651-692-6084', 1, 'Ilene', '69', 'sgracewoodq@plala.or.jp', '1972-11-01', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('libero', 'Karlotta', 'Robe', '537-379-1572', 5, 'Fuller', '502', 'krober@uiuc.edu', '2004-08-11', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ultrices', 'Sibbie', 'Andrusov', '386-941-7456', 13, 'Mitchell', '4146', 'sandrusovs@google.com.au', '1977-06-17', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('posuere', 'Korney', 'Crabtree', '194-424-6575', 13, 'Raven', '67662', 'kcrabtreet@usgs.gov', '1969-01-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('massa', 'Coral', 'Mainwaring', '169-550-0798', 3, 'Packers', '31', 'cmainwaringu@forbes.com', '1970-03-14', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eu', 'Fanchon', 'McCaskill', '160-735-6281', 5, 'Eliot', '79574', 'fmccaskillv@gmpg.org', '1989-02-11', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('dolor', 'Kaja', 'Jewks', '277-705-0423', 4, 'Bobwhite', '62476', 'kjewksw@macromedia.com', '1999-08-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('turpis', 'Matilde', 'Hughill', '741-341-4545', 2, 'Sunfield', '8', 'mhughillx@devhub.com', '1992-11-27', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('curabitur', 'Ketty', 'Easterby', '925-628-7486', 2, 'Dayton', '102', 'keasterbyy@si.edu', '1998-04-12', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('rutrum', 'Elvis', 'Gornal', '530-937-8945', 13, 'Debra', '91783', 'egornalz@fda.gov', '2001-02-21', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('at', 'Matthias', 'Bramstom', '653-556-3675', 10, 'Colorado', '2695', 'mbramstom10@addthis.com', '1976-02-19', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('molestie', 'Marsha', 'Serman', '161-549-6647', 8, 'Arkansas', '017', 'mserman11@si.edu', '1982-05-09', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('quam', 'Weston', 'Thackham', '997-739-0888', 11, 'Clyde Gallagher', '29972', 'wthackham12@tiny.cc', '1984-05-29', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('velit', 'Norene', 'Borthwick', '996-314-9183', 7, 'Thompson', '50', 'nborthwick13@canalblog.com', '1970-06-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('felis', 'Gary', 'Goldsbrough', '651-619-2188', 9, 'Delaware', '54359', 'ggoldsbrough14@ox.ac.uk', '1988-12-16', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('nonummy', 'Johnette', 'Murdy', '210-244-2443', 9, 'Burrows', '80807', 'jmurdy15@bravesites.com', '1971-11-05', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('lacus', 'Amandi', 'Colvie', '768-260-6670', 9, 'Buell', '180', 'acolvie16@macromedia.com', '1991-12-02', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('quam', 'Juline', 'Johananov', '750-788-9285', 5, 'Bartelt', '6794', 'jjohananov17@google.es', '1971-04-22', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ultrices', 'Dee dee', 'Halsho', '410-184-8969', 1, 'Mallard', '12', 'dhalsho18@cbsnews.com', '1998-08-01', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('pulvinar', 'Mac', 'Langshaw', '322-903-5773', 4, 'Northwestern', '29', 'mlangshaw19@blogger.com', '1983-04-22', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('imperdiet', 'Gregory', 'Bummfrey', '296-534-6378', 1, 'Lerdahl', '062', 'gbummfrey1a@t.co', '1970-06-03', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('mauris', 'Gunter', 'Speedin', '871-302-5696', 10, 'Shopko', '9', 'gspeedin1b@yandex.ru', '1980-12-24', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('orci', 'Bruno', 'Potticary', '845-366-9037', 1, 'Del Mar', '4235', 'bpotticary1c@mozilla.com', '1969-12-05', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('lacinia', 'Jennica', 'Fouracres', '334-776-4785', 9, 'Valley Edge', '28968', 'jfouracres1d@mac.com', '1982-04-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('amet', 'Jammie', 'Shurrocks', '667-594-8934', 1, 'Heath', '85', 'jshurrocks1e@gmpg.org', '1992-11-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('amet', 'Ellwood', 'Sexstone', '325-721-2392', 9, 'Swallow', '5118', 'esexstone1f@example.com', '1987-01-14', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('libero', 'Ivar', 'Frostdick', '911-335-7370', 13, 'Fisk', '74023', 'ifrostdick1g@goo.ne.jp', '2000-06-01', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('feugiat', 'Eimile', 'Shreeves', '606-516-6821', 7, 'Grayhawk', '40201', 'eshreeves1h@globo.com', '1981-05-15', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('felis', 'Ferdy', 'Draycott', '197-648-4998', 9, 'Carey', '1138', 'fdraycott1i@goodreads.com', '1999-03-20', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('in', 'Friederike', 'Decreuze', '923-328-4775', 2, 'Stang', '1324', 'fdecreuze1j@rakuten.co.jp', '1987-04-21', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('turpis', 'Edgard', 'Buse', '242-748-2089', 9, 'Rusk', '81', 'ebuse1k@fema.gov', '1975-05-03', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('imperdiet', 'Krishna', 'Livingston', '234-946-8109', 8, 'Lunder', '02108', 'klivingston1l@sbwire.com', '1982-01-29', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('non', 'Kent', 'Chadbourne', '192-246-2372', 7, 'Mesta', '0', 'kchadbourne1m@stumbleupon.com', '1983-05-16', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ligula', 'Tait', 'Osanne', '167-341-2378', 2, 'Oneill', '74733', 'tosanne1n@smugmug.com', '2000-11-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('odio', 'Tybalt', 'Ruprechter', '155-913-9854', 5, 'Menomonie', '79454', 'truprechter1o@cnet.com', '1992-01-14', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sapien', 'Jamill', 'Dudney', '643-488-3818', 13, 'Mandrake', '5', 'jdudney1p@ustream.tv', '1994-11-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('primis', 'Dara', 'Windows', '458-126-7518', 5, 'Lake View', '023', 'dwindows1q@g.co', '1979-06-03', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('hac', 'Woodman', 'Darwen', '984-460-5537', 6, 'Cherokee', '234', 'wdarwen1r@weebly.com', '1993-05-10', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eget', 'Ingaberg', 'Di Antonio', '477-479-9910', 2, 'Fordem', '087', 'idiantonio1s@nymag.com', '1975-09-26', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('mollis', 'Hart', 'Petheridge', '961-590-9564', 10, 'Homewood', '5922', 'hpetheridge1t@ocn.ne.jp', '1984-04-04', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('dui', 'Hasheem', 'Horsfield', '343-713-8419', 3, 'North', '43', 'hhorsfield1u@storify.com', '1969-06-08', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('consequat', 'Ulrike', 'Bosanko', '125-667-2571', 9, 'Tennessee', '5034', 'ubosanko1v@friendfeed.com', '1987-05-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('viverra', 'Carlin', 'Godley', '341-849-3368', 4, 'Colorado', '96042', 'cgodley1w@engadget.com', '1985-05-08', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('quam', 'Warner', 'Williment', '804-532-0667', 12, 'Mariners Cove', '45', 'wwilliment1x@flavors.me', '2000-01-24', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('justo', 'Sarena', 'Yanyushkin', '807-601-2519', 6, 'Buell', '00', 'syanyushkin1y@sun.com', '2002-02-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('at', 'Cissiee', 'Heliot', '151-925-5024', 13, 'Sutteridge', '61', 'cheliot1z@yellowpages.com', '2000-04-14', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eros', 'Celestyn', 'McGilvray', '267-352-8739', 13, 'Main', '6325', 'cmcgilvray20@bbb.org', '1994-12-19', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('duis', 'Evelyn', 'Flannery', '332-979-6352', 12, 'Roxbury', '66007', 'eflannery21@vinaora.com', '1974-07-02', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('phasellus', 'Kaja', 'Leicester', '167-648-9920', 3, 'Riverside', '937', 'kleicester22@constantcontact.com', '1973-06-18', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eget', 'Consuelo', 'Kindle', '387-171-9976', 11, 'Eliot', '1849', 'ckindle23@hao123.com', '1987-07-20', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vulputate', 'Aldon', 'Longford', '702-254-0541', 4, 'Lerdahl', '73', 'alongford24@microsoft.com', '1978-01-01', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ipsum', 'Eddy', 'Clancey', '948-115-1153', 3, 'Nobel', '1', 'eclancey25@cbsnews.com', '1979-12-28', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('nulla', 'Brittne', 'Morriarty', '581-394-4887', 3, 'Nobel', '77', 'bmorriarty26@goo.ne.jp', '1984-04-13', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('ante', 'Enrico', 'Gerckens', '663-508-9749', 4, 'Waywood', '32563', 'egerckens27@dropbox.com', '1989-03-01', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('velit', 'Pennie', 'Kurton', '897-419-1928', 12, 'Grover', '72922', 'pkurton28@gov.uk', '1981-01-07', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('at', 'Bee', 'Hurren', '445-864-3956', 10, 'Elgar', '81', 'bhurren29@usgs.gov', '1992-06-15', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sed', 'Ephrayim', 'Owtram', '148-517-3364', 3, 'Hudson', '1', 'eowtram2a@nifty.com', '1969-04-05', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sed', 'Peirce', 'Hungerford', '682-506-1771', 3, 'Dixon', '78', 'phungerford2b@abc.net.au', '1988-04-17', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('nullam', 'Billy', 'Harbour', '718-911-4210', 8, 'Duke', '62089', 'bharbour2c@yolasite.com', '1971-12-29', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vehicula', 'Aymer', 'Curcher', '306-108-6873', 1, 'Mcbride', '3453', 'acurcher2d@shutterfly.com', '1969-03-25', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vivamus', 'Janine', 'Flemyng', '196-767-2675', 11, 'Pankratz', '4', 'jflemyng2e@yelp.com', '1986-11-08', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('suspendisse', 'Anna', 'Brende', '201-820-4562', 1, 'Crescent Oaks', '75', 'abrende2f@nyu.edu', '1989-01-22', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('luctus', 'Dru', 'Pickrell', '148-320-5788', 8, 'Ruskin', '88', 'dpickrell2g@meetup.com', '1985-03-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('erat', 'Rurik', 'Perrinchief', '360-318-9443', 3, 'Melvin', '700', 'rperrinchief2h@edublogs.org', '1994-01-24', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('amet', 'Cecilio', 'Reddan', '354-745-2585', 1, 'East', '0', 'creddan2i@cyberchimps.com', '1988-12-03', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('erat', 'Annette', 'Houselee', '386-233-7196', 11, 'Fallview', '18', 'ahouselee2j@craigslist.org', '1994-07-19', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('vehicula', 'Cornall', 'ducarme', '407-765-0435', 10, 'Claremont', '84535', 'cducarme2k@barnesandnoble.com', '1986-11-26', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('sed', 'Sayre', 'Quartly', '586-786-7956', 6, 'Fieldstone', '69763', 'squartly2l@scribd.com', '1969-07-19', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('suspendisse', 'Katey', 'Agge', '695-283-2404', 9, 'Holmberg', '190', 'kagge2m@eventbrite.com', '1996-05-29', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eu', 'Fonzie', 'Farrah', '451-863-6582', 5, 'Stephen', '4', 'ffarrah2n@japanpost.jp', '1998-04-30', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('nulla', 'Nat', 'William', '580-919-0323', 6, 'Dryden', '825', 'nwilliam2o@yolasite.com', '1978-11-18', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('justo', 'Jayme', 'Heathfield', '820-610-2036', 12, 'Orin', '71', 'jheathfield2p@latimes.com', '1984-10-19', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('lacus', 'Joby', 'Agnolo', '363-963-9633', 12, 'Scoville', '1908', 'jagnolo2q@angelfire.com', '1984-07-29', '2023-04-04');
insert into registro.CONTACTO_EMERGENCIA (Relacion, Nombres, Apellidos, Telefono, Sector_ID, Calle, Numero_Casa, Correo_Electronico, Fecha_Nacimiento, Fecha_Registro) values ('eu', 'Tomkin', 'Donnelly', '493-159-6730', 7, 'Melby', '92377', 'tdonnelly2r@cbslocal.com', '1989-05-06', '2023-04-04');

--COLOR
INSERT INTO registro.COLOR (Nombre)
VALUES
('Negro'),
('Azul'),
('Marrón'),
('Gris'),
('Verde'),
('Naranja'),
('Rosa'),
('Púrpura'),
('Rojo'),
('Blanco'),
('Amarillo');

--RAZAS
INSERT INTO registro.RAZAS (Nombre, Especie_ID) 
VALUES 
('Labrador Retriever', 1), 
('Pastor Alemán', 1), 
('Bulldog Francés', 1), 
('Golden Retriever', 1), 
('Poodle', 1), 
('Bulldog Inglés', 1), 
('Rottweiler', 1), 
('Boxer', 1), 
('Chihuahua', 1),
('Husky Siberiano', 1),
('Siamés', 2), 
('Persa', 2), 
('Bengalí', 2), 
('Angora', 2), 
('Gato siamés', 2);


Delete registro.MASCOTAS
DBCC CHECKIDENT('registro.MASCOTAS', RESEED, 0);

--MASCOTAS
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Orren', 1, '2022-05-12', '2007-03-02', 13, '2022-11-24', '3XL', 1, 7, 36, '0703-2858', 'blandit ultrices enim lorem', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Hendrick', 2, '2022-12-09', '2000-08-12', 8, '2022-06-09', '2XL', 1, 4, 18, '10812-967', 'arcu libero rutrum ac', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Aidan', 3, '2022-08-14', '2001-05-26', 32, '2023-03-08', 'XS', 1, 9, 10, '49967-907', 'est donec odio justo', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Roby', 2, '2022-12-27', '2000-10-31', 2, '2022-10-17', '2XL', 1, 4, 3, '16590-457', 'lacus at', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Fara', 2, '2023-01-05', '2021-07-23', 10, '2022-02-14', 'M', 1, 9, 35, '51801-007', 'eleifend luctus', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Robinett', 6, '2023-01-07', '2012-11-10', 3, '2022-10-11', 'L', 1, 3, 33, '68788-9125', 'id mauris vulputate', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Carina', 1, '2022-05-02', '2016-01-30', 35, '2023-01-04', '2XL', 1, 9, 4, '0173-0526', 'porttitor lacus', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Sydelle', 4, '2022-06-04', '2021-12-03', 13, '2022-01-06', 'L', 1, 3, 17, '11535-128', 'vitae nisi nam', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Winni', 2, '2022-10-06', '2014-07-29', 13, '2022-02-09', 'L', 1, 3, 10, '51079-104', 'vitae consectetuer eget rutrum', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Taddeusz', 1, '2023-03-09', '2001-01-15', 4, '2022-01-02', '3XL', 1, 9, 8, '50425-011', 'donec diam', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ronny', 4, '2022-12-21', '2005-11-11', 30, '2022-01-23', 'S', 1, 4, 28, '76472-1155', 'ipsum dolor sit amet', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dael', 2, '2022-11-19', '2019-06-28', 39, '2022-03-23', 'XS', 1, 4, 35, '24236-005', 'massa donec', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Knox', 1, '2023-03-11', '2011-02-16', 34, '2022-02-08', 'XL', 1, 9, 35, '53808-0970', 'nulla tellus in sagittis', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Mersey', 4, '2023-03-21', '2015-10-06', 20, '2022-04-08', 'S', 1, 6, 46, '45802-966', 'duis bibendum', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dody', 2, '2022-06-13', '2019-02-18', 38, '2022-11-11', 'M', 1, 8, 5, '55289-373', 'dolor sit amet consectetuer', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Tobye', 5, '2022-05-22', '2005-01-07', 9, '2022-06-19', 'M', 1, 10, 36, '0363-0516', 'vel accumsan tellus nisi', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ephrem', 3, '2022-07-06', '2019-05-04', 27, '2023-01-21', 'XS', 1, 1, 22, '75892-001', 'primis in faucibus orci', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Benedikt', 4, '2022-12-28', '2002-06-19', 17, '2022-01-28', 'XL', 1, 10, 45, '65692-0126', 'leo odio porttitor id', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Mano', 1, '2023-02-14', '2014-07-02', 9, '2023-01-31', 'XL', 1, 5, 15, '68703-071', 'condimentum curabitur in', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Aggie', 2, '2023-03-12', '2018-09-27', 36, '2022-04-03', 'M', 1, 5, 22, '0904-0358', 'tortor id nulla', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Hortensia', 6, '2022-04-28', '2015-05-21', 38, '2022-02-15', 'L', 1, 1, 6, '0268-6141', 'eget orci vehicula condimentum', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ciro', 6, '2023-03-17', '2008-08-08', 12, '2022-04-03', '2XL', 1, 10, 14, '49884-746', 'quis libero', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Trudie', 3, '2022-05-15', '2020-08-20', 23, '2022-10-28', '2XL', 1, 4, 6, '68788-9798', 'pulvinar lobortis', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Salmon', 6, '2023-03-22', '2003-03-06', 37, '2023-03-06', '2XL', 1, 9, 40, '59762-0057', 'pede malesuada', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Gigi', 1, '2022-04-10', '2010-11-19', 34, '2022-12-21', 'M', 1, 9, 50, '0615-4575', 'lacus at velit vivamus', 2, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Brennan', 2, '2023-03-18', '2000-12-24', 31, '2023-02-23', 'XL', 1, 1, 1, '0054-0102', 'nisl duis', 2, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Taffy', 3, '2022-08-30', '2011-07-30', 9, '2022-04-29', 'S', 1, 5, 11, '64778-1233', 'volutpat quam pede', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Berny', 4, '2023-03-22', '2003-09-17', 24, '2022-05-20', 'M', 1, 3, 19, '49349-268', 'in blandit ultrices enim', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Lonny', 4, '2022-12-22', '2011-07-05', 1, '2022-11-16', 'L', 1, 7, 1, '0093-7157', 'vel augue vestibulum rutrum', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Boot', 1, '2022-08-07', '2015-08-13', 2, '2022-03-17', '3XL', 1, 10, 41, '68016-142', 'accumsan odio curabitur', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Jeannine', 1, '2022-09-24', '2000-09-22', 26, '2022-07-23', 'XL', 1, 9, 37, '35356-971', 'convallis eget', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Jeff', 1, '2022-06-24', '2006-06-01', 30, '2022-01-06', 'M', 1, 7, 34, '14060-006', 'dolor vel est donec', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Barty', 1, '2022-09-20', '2009-01-24', 13, '2022-08-02', 'L', 1, 2, 35, '62584-747', 'justo in', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Hewe', 2, '2022-09-02', '2005-02-16', 2, '2022-06-10', 'S', 1, 1, 30, '50051-0008', 'mauris lacinia sapien', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Arlyn', 3, '2022-06-15', '2009-03-25', 5, '2023-01-26', '3XL', 1, 8, 3, '0944-2620', 'elementum pellentesque', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ashely', 4, '2022-08-23', '2020-11-27', 3, '2023-01-08', 'XL', 1, 9, 38, '10056-701', 'amet eros', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ruby', 4, '2023-02-15', '2002-10-02', 6, '2022-04-03', 'M', 1, 9, 6, '51655-141', 'nisi at nibh', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Quill', 4, '2022-11-02', '2010-11-27', 3, '2023-03-26', 'XL', 1, 5, 21, '46708-033', 'tortor duis mattis', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Rory', 6, '2022-09-04', '2019-05-20', 14, '2022-07-06', 'XS', 1, 5, 1, '41250-090', 'vestibulum sit amet', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Edith', 3, '2023-03-31', '2008-06-01', 31, '2022-09-18', 'XL', 1, 5, 19, '54458-932', 'luctus cum sociis natoque', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Sal', 6, '2022-06-20', '2021-09-23', 39, '2022-02-24', '2XL', 1, 2, 23, '0173-0859', 'varius nulla facilisi', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Livia', 6, '2022-06-17', '2003-04-09', 3, '2022-09-03', 'L', 1, 5, 22, '24794-225', 'etiam faucibus', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Rhonda', 6, '2023-03-27', '2009-08-25', 36, '2022-07-14', 'XS', 1, 5, 48, '0268-6538', 'libero rutrum', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Wanids', 2, '2023-03-24', '2013-11-18', 1, '2022-03-03', 'S', 1, 1, 8, '36987-3174', 'convallis nulla', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Mannie', 5, '2023-03-24', '2016-04-21', 23, '2022-07-30', 'XS', 1, 8, 26, '63824-279', 'tristique est et', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dorothee', 6, '2022-08-31', '2002-12-03', 11, '2022-07-12', '3XL', 1, 1, 27, '0615-6576', 'eget orci vehicula condimentum', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Karole', 1, '2022-06-29', '2000-02-04', 14, '2022-09-10', 'M', 1, 5, 26, '64616-079', 'hendrerit at vulputate vitae', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Yoshiko', 6, '2023-03-21', '2006-01-26', 24, '2022-08-26', 'XS', 1, 5, 19, '54868-5750', 'eros elementum', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Tawnya', 5, '2022-09-25', '2002-10-16', 28, '2022-05-06', 'XS', 1, 10, 31, '10096-0184', 'a nibh in quis', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Burton', 3, '2022-06-14', '2020-09-06', 36, '2022-10-25', 'XL', 1, 6, 10, '0024-5843', 'lacus curabitur at', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Forbes', 6, '2022-07-23', '2001-05-19', 33, '2022-09-06', '3XL', 2, 13, 61, '57955-2790', 'nisi at nibh in', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Moises', 3, '2022-12-22', '2002-04-13', 33, '2022-02-17', 'XS', 2, 15, 96, '59886-330', 'cum sociis natoque', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Sigvard', 3, '2022-07-19', '2008-03-06', 22, '2022-11-15', '3XL', 2, 14, 77, '57520-0524', 'non velit nec', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Berky', 4, '2022-05-29', '2018-02-08', 35, '2022-07-08', 'XS', 2, 15, 87, '10122-902', 'cras pellentesque volutpat dui', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Margit', 4, '2022-10-19', '2012-03-31', 39, '2022-03-11', 'L', 2, 13, 58, '49288-0855', 'mattis egestas', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Rowney', 6, '2022-10-01', '2017-11-09', 5, '2023-01-06', 'M', 2, 11, 90, '59387-001', 'in lectus pellentesque', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Iris', 6, '2022-12-07', '2002-08-12', 8, '2022-05-06', 'M', 2, 13, 86, '49288-0453', 'integer aliquet', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Lana', 3, '2022-05-27', '2001-05-25', 40, '2023-02-04', 'XL', 2, 14, 68, '49349-272', 'porttitor lorem id', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Erena', 3, '2022-05-17', '2010-04-22', 8, '2022-08-26', 'L', 2, 15, 67, '36987-1938', 'pretium iaculis diam erat', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Charo', 4, '2022-12-25', '2011-10-04', 14, '2022-03-20', 'S', 2, 11, 66, '63629-2868', 'dui vel', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Amye', 3, '2022-08-09', '2006-07-25', 17, '2023-02-09', 'S', 2, 14, 95, '36987-1801', 'lobortis vel dapibus', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Viviene', 5, '2023-02-20', '2015-07-22', 2, '2022-03-08', 'XL', 2, 14, 91, '51346-069', 'posuere cubilia curae donec', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Marnie', 5, '2023-01-08', '2000-12-10', 5, '2022-04-05', '2XL', 2, 13, 76, '61995-2383', 'ut dolor morbi', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Herby', 1, '2022-04-19', '2003-12-09', 27, '2022-06-17', '3XL', 2, 13, 59, '54838-501', 'quis orci nullam', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dud', 5, '2022-09-05', '2001-02-25', 2, '2022-03-22', 'S', 2, 12, 51, '0002-8315', 'lacus morbi', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('James', 5, '2022-11-01', '2004-05-20', 33, '2022-08-09', 'XL', 2, 12, 90, '55714-1503', 'quis turpis sed', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Homer', 5, '2022-04-03', '2009-10-20', 6, '2022-05-16', 'S', 2, 11, 55, '0472-1261', 'cras mi pede malesuada', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Roda', 5, '2022-04-08', '2003-05-26', 12, '2022-07-11', 'XL', 2, 12, 67, '58479-008', 'pulvinar sed nisl nunc', 2, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dino', 3, '2022-11-28', '2006-04-20', 28, '2022-05-15', '3XL', 2, 13, 93, '68788-9792', 'porttitor pede justo eu', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ari', 3, '2023-02-20', '2004-10-06', 36, '2022-11-15', '2XL', 2, 15, 84, '10006-010', 'faucibus orci luctus et', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Morgen', 3, '2022-12-30', '2008-01-05', 30, '2023-01-14', 'XS', 2, 14, 68, '59779-003', 'tincidunt in', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Elwira', 1, '2022-10-05', '2008-10-09', 16, '2022-10-22', 'XL', 2, 14, 61, '64960-000', 'diam in', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Cleopatra', 2, '2022-05-25', '2003-06-13', 39, '2022-01-15', 'XS', 2, 15, 75, '60289-050', 'libero ut massa volutpat', 2, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Annabal', 4, '2022-10-23', '2009-06-04', 1, '2022-03-15', 'M', 2, 12, 95, '68084-180', 'nunc purus phasellus in', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Gan', 4, '2022-10-10', '2002-11-22', 11, '2023-03-03', '2XL', 2, 13, 53, '55154-5376', 'imperdiet nullam orci', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Dodie', 4, '2022-10-20', '2011-08-29', 39, '2023-03-17', 'M', 2, 12, 64, '10742-8152', 'venenatis tristique fusce', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Moss', 3, '2023-01-27', '2002-12-25', 13, '2023-02-08', 'XS', 2, 14, 70, '41520-323', 'non mauris morbi', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Kareem', 2, '2022-04-25', '2009-12-18', 15, '2023-02-06', '2XL', 2, 13, 74, '50730-1016', 'sapien sapien', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Rubi', 2, '2022-07-07', '2013-06-18', 36, '2022-09-27', '2XL', 2, 12, 96, '21695-690', 'id nisl venenatis lacinia', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Rosaline', 5, '2022-10-05', '2017-11-18', 17, '2022-09-10', '3XL', 2, 13, 85, '60760-812', 'nulla facilisi cras', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Gifford', 6, '2022-08-10', '2008-07-02', 19, '2022-11-04', 'XS', 2, 11, 53, '57520-0353', 'semper porta', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Aime', 2, '2022-06-28', '2005-01-20', 28, '2022-10-30', 'S', 2, 14, 52, '49288-0227', 'vulputate vitae', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Pam', 4, '2022-05-26', '2015-05-03', 32, '2022-09-28', 'XS', 2, 11, 94, '49288-0148', 'id ligula suspendisse', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Enrique', 6, '2023-03-17', '2001-11-11', 40, '2022-11-05', 'M', 2, 12, 67, '11822-1403', 'viverra eget congue', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Frannie', 3, '2022-12-29', '2019-01-31', 36, '2022-06-26', 'S', 2, 11, 87, '51009-116', 'a feugiat et eros', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Ive', 5, '2022-09-07', '2005-05-13', 9, '2022-09-21', '2XL', 2, 13, 60, '36987-2482', 'ante ipsum', 6, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Crystal', 1, '2022-12-10', '2010-01-09', 8, '2022-12-25', 'S', 2, 12, 77, '53808-0985', 'justo morbi', 2, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Karla', 4, '2022-05-29', '2009-09-23', 33, '2022-06-08', 'L', 2, 14, 80, '58118-2531', 'aliquet maecenas', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Zia', 1, '2022-09-28', '2003-07-02', 23, '2022-04-12', 'L', 2, 12, 84, '60268-0001', 'libero ut massa volutpat', 8, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Albertina', 2, '2023-02-01', '2003-02-04', 19, '2022-07-20', 'XS', 2, 13, 89, '62007-012', 'leo odio', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Lizzie', 3, '2022-09-05', '2011-07-10', 17, '2022-09-06', 'XL', 2, 13, 56, '68084-542', 'amet eros', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Nelson', 3, '2022-08-11', '2004-03-01', 26, '2022-04-04', '2XL', 2, 11, 70, '50845-0031', 'enim lorem ipsum', 10, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Cyndie', 5, '2022-09-02', '2016-06-26', 11, '2022-10-01', '2XL', 2, 15, 71, '44597-5605', 'justo maecenas', 11, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Kali', 5, '2022-05-27', '2010-12-07', 22, '2022-11-07', '3XL', 2, 14, 84, '37000-404', 'imperdiet sapien urna pretium', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Moll', 5, '2022-08-06', '2010-02-01', 13, '2022-03-10', 'L', 2, 11, 95, '53262-001', 'erat eros viverra eget', 4, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Duane', 6, '2022-12-31', '2013-04-18', 20, '2022-09-04', '2XL', 2, 13, 75, '0074-4456', 'ac tellus', 3, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Bernardine', 5, '2022-10-15', '2021-07-12', 25, '2022-08-22', 'XS', 2, 15, 93, '0067-3999', 'magna vulputate luctus cum', 1, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Faye', 2, '2022-08-10', '2000-01-30', 34, '2023-02-11', 'S', 2, 12, 62, '30805-009', 'pellentesque volutpat dui maecenas', 5, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Bonnie', 4, '2022-06-29', '2012-08-08', 10, '2022-10-04', '2XL', 2, 12, 74, '0074-2277', 'turpis enim blandit', 7, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');
insert into registro.MASCOTAS (Nombre, Sexo_ID, Fecha_Registro, Fecha_Nacimiento, Peso, Fecha_Ultimo_Celo, Tamaño, Especie_ID, Raza_Primaria_ID, Dueño_ID, Microchip, Nota, Color_ID, Tarjeta_File_Name, Tarjeta_File_Path, Foto_File_Name, Foto_File_Path) values ('Germana', 1, '2023-03-21', '2019-08-03', 13, '2023-02-16', 'L', 2, 12, 97, '51672-4069', 'libero non mattis pulvinar', 9, 'File.pdf', 'C:/Hotel_Mascotas/Mascotas/file/', 'FotoFile.jpg', 'C:/Hotel_Mascotas/Mascotas/fotos/');

--MASCOTAS_CONDICION
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (5, 93, '2022-04-29', 'pharetra');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (8, 57, '2022-06-26', 'ut ultrices');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 73, '2022-10-11', 'ut massa');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (7, 54, '2022-06-01', 'sollicitudin mi sit');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 20, '2022-05-28', 'consequat');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (2, 75, '2022-08-12', 'volutpat quam');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 9, '2022-11-02', 'primis in');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 53, '2022-09-14', 'nonummy integer');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (4, 81, '2023-01-26', 'hac');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 6, '2022-11-28', 'suspendisse');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 94, '2022-09-01', 'augue');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (4, 29, '2022-12-06', 'semper est quam');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 53, '2022-05-04', 'parturient montes nascetur');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 46, '2022-05-30', 'consectetuer');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 39, '2022-11-13', 'mattis nibh ligula');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (5, 24, '2022-05-11', 'curae mauris');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 99, '2023-02-26', 'risus auctor sed');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (4, 84, '2022-06-11', 'sit amet');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 11, '2022-11-03', 'metus');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (10, 68, '2023-02-18', 'eros viverra');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 24, '2022-08-16', 'interdum in ante');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (8, 99, '2022-12-12', 'felis sed interdum');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 87, '2022-07-28', 'lectus pellentesque at');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (1, 2, '2022-05-18', 'ut volutpat');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 42, '2022-10-10', 'porttitor');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (10, 48, '2022-07-17', 'pede');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (1, 97, '2023-02-15', 'mauris enim leo');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (8, 6, '2022-04-17', 'ipsum ac tellus');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (7, 86, '2022-04-12', 'viverra dapibus nulla');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 7, '2023-03-05', 'duis');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 89, '2023-03-15', 'sed augue aliquam');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 48, '2022-10-20', 'at turpis');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 77, '2022-12-30', 'vulputate elementum');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 25, '2023-02-17', 'amet consectetuer');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (5, 89, '2023-02-26', 'magna vestibulum');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 27, '2022-08-27', 'erat eros');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 11, '2022-10-07', 'platea');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 81, '2022-11-26', 'lacus');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (10, 79, '2022-06-10', 'fermentum');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 2, '2022-05-12', 'ut rhoncus');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 60, '2022-04-05', 'at nulla');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (10, 93, '2022-05-29', 'ut');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (2, 93, '2023-01-31', 'vulputate');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (9, 41, '2022-10-22', 'ultrices posuere cubilia');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (3, 72, '2022-06-30', 'libero rutrum ac');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (2, 84, '2022-07-31', 'venenatis non');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (8, 69, '2023-03-22', 'consequat in consequat');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (7, 68, '2022-07-03', 'natoque');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (6, 6, '2022-12-28', 'condimentum id luctus');
insert into registro.MASCOTA_CONDICION (Condicion_ID, Mascota_ID, Fecha_Registro, Descripcion) values (10, 44, '2022-07-17', 'quam');

--MASCOTA_CONTACTO
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (1, 44, '2022-12-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (2, 58, '2022-09-18');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (3, 50, '2022-06-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (4, 81, '2023-02-08');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (5, 64, '2023-02-15');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (6, 40, '2023-01-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (7, 64, '2022-12-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (8, 44, '2023-02-25');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (9, 23, '2022-07-13');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (10, 23, '2022-11-14');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (11, 70, '2022-12-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (12, 7, '2022-04-06');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (13, 50, '2023-02-22');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (14, 90, '2022-10-04');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (15, 48, '2023-01-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (16, 66, '2022-06-22');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (17, 20, '2023-02-27');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (18, 44, '2022-08-31');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (19, 53, '2022-07-24');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (20, 45, '2022-09-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (21, 90, '2022-10-15');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (22, 2, '2022-05-24');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (23, 4, '2022-10-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (24, 5, '2022-08-18');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (25, 2, '2022-09-25');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (26, 73, '2022-07-09');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (27, 29, '2022-10-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (28, 31, '2023-04-03');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (29, 73, '2023-01-08');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (30, 45, '2023-02-27');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (31, 57, '2023-01-03');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (32, 67, '2023-03-15');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (33, 65, '2023-03-18');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (34, 81, '2022-09-06');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (35, 24, '2022-06-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (36, 31, '2022-07-25');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (37, 17, '2022-11-04');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (38, 5, '2022-11-24');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (39, 87, '2022-05-23');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (40, 35, '2022-10-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (41, 20, '2022-06-12');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (42, 57, '2022-09-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (43, 6, '2022-10-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (44, 49, '2023-03-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (45, 58, '2022-04-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (46, 29, '2022-10-29');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (47, 46, '2022-04-22');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (48, 23, '2023-02-04');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (49, 9, '2022-08-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (50, 98, '2023-02-07');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (51, 7, '2022-12-13');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (52, 9, '2022-09-19');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (53, 54, '2022-09-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (54, 68, '2023-02-12');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (55, 80, '2023-01-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (56, 33, '2022-10-04');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (57, 21, '2022-08-26');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (58, 50, '2022-12-27');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (59, 4, '2022-04-11');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (60, 83, '2023-01-31');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (61, 21, '2023-01-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (62, 42, '2022-05-25');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (63, 11, '2022-07-16');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (64, 24, '2023-03-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (65, 21, '2022-04-29');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (66, 95, '2022-06-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (67, 9, '2022-11-22');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (68, 75, '2022-08-23');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (69, 12, '2023-02-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (70, 58, '2022-10-13');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (71, 66, '2022-07-06');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (72, 34, '2023-01-06');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (73, 42, '2023-02-16');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (74, 45, '2023-03-23');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (75, 42, '2022-04-24');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (76, 82, '2022-07-02');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (77, 74, '2023-03-14');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (78, 62, '2023-02-22');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (79, 14, '2022-05-27');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (80, 26, '2022-09-03');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (81, 94, '2023-01-20');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (82, 25, '2023-03-08');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (83, 23, '2023-03-18');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (84, 60, '2022-04-30');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (85, 90, '2023-02-02');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (86, 79, '2023-04-01');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (87, 1, '2022-11-02');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (88, 23, '2022-05-11');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (89, 21, '2023-03-14');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (90, 55, '2022-07-15');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (91, 22, '2023-01-15');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (92, 25, '2022-05-01');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (93, 78, '2022-04-29');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (94, 1, '2022-08-21');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (95, 90, '2022-04-17');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (96, 53, '2022-09-05');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (97, 54, '2022-05-03');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (98, 78, '2022-12-12');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (99, 40, '2022-04-23');
insert into registro.MASCOTA_CONTACTO (Contacto_Emergencia_ID, Mascota_ID, Fecha_Registro) values (100, 30, '2022-12-02');

